name: DAST with OWASP ZAP

on:
  # Configure o gatilho para o workflow, por exemplo, em push na branch main
  push:
    branches: [ master ]

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build da imagem Docker
      - name: Build Docker image
        run: docker build -t appsecco/dvcsharp .

      # Executar o container Docker em segundo plano
      - name: Run Docker container
        run: docker run -d --name dvcsharp -it -p 5000:5000 appsecco/dvcsharp

      # Aguardar a inicialização da aplicação (ajuste o tempo conforme necessário)
      - name: Wait for application to start
        run: sleep 30

      # Executar o ZAP
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.13.0
        env:
          ZAP_AUTH_HEADER_VALUE: "Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==" # Substitua pelas suas credenciais
          ZAP_AUTH_HEADER: "Authorization"
        with:
          allow_issue_writing: false
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          target: "http://localhost:5000" # Ajuste a porta se necessário
          rules_file_name: config/zap/rule-config.tsv # Caminho para o arquivo de regras
          fail_action: true
          cmd_options: '-z "-configFile /zap/wrk/config/zap/options.prop" -a'
